config/routes.rb
Rails.application.routes.draw do
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html  

  root "dashboard#index"
  get "/movie/:id" => "dashboard#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :ratings, foreign_key: "movieId"

    def self.hits 
        all.select{|movie| movie.average_rating > 4.5}
    end

    def average_rating
        if ratings.count > 0
            average = ratings.pluck(:rating).sum / ratings.count
            average.round(1)
        else
            0
        end
    end
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :movie, foreign_key: "movieId"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def say_hello
    puts "*" *50
    puts "hi"
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:suit, :color, :value)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    say_hello
    @movies = Movie.all
  end

  def show
    movieId = params["id"]
    @movie = Movie.find_by(movieId: movieId)
    @ratings = @movie.ratings
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :suit %>
    <%= form.text_field :suit %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Suit</th>
      <th>Color</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.suit %></td>
        <td><%= card.color %></td>
        <td><%= card.value %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suit:</strong>
  <%= @card.suit %>
</p>

<p>
  <strong>Color:</strong>
  <%= @card.color %>
</p>

<p>
  <strong>Value:</strong>
  <%= @card.value %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/dashboard/index.html.erb
<div class="container">
  <h1 class="page-header">Movies</h1>
  <%= Faker::Name.name  %>
  <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <th>Movie ID</th>
      <th>Title</th>
      <th>Genres</th>
    </thead>

    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.movieId %></td>
          <td><%= movie.title %></td>
          <td><%= movie.genres %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/show.html.erb
<h1><%= @movie %></h1>
<h3>Average Rating: <%= @movie.average_rating %></h3>

<ul>
  <% @ratings.each do |rating|%>
    <li><%= rating.rating %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movielens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>